### ISSUE TITLE
Consider using Type::Tiny instead of depending on Mouse for types.

### ISSUE THREAD

**Issue by tobyink** [pokutuna/p5-Text-Xslate-Bridge-TypeDeclaration#1]
1. A lot of Moose/Moo users don't like Mouse because it doesn't play nicely with them.
2. If the optional Type::Tiny::XS is installed, Type::Tiny's type checks are as fast as Mouse's.
3. Type::Tiny offers more built-in types than Mouse, such as `Tuple[Num, Num, Num]` which will check that `$var` is an arrayref of three numbers (perhaps a point in 3D space?), and `Map[Int, ArrayRef]` which will check that `$var` is a hashref with integer keys and ArrayRef values.

Type::Tiny has been designed to be compatible with Mouse (and Moose and Moo) from the start, so it should only be a few lines of code to switch over. I'd be happy to make a pull request if this is a feature you'd be interested in.

**Comment by pokutuna** [comment]
Thank you for suggestion.
I have never used Type::Tiny, but it is looks good. I'll try to update this module to use Type::Tiny. Please make a pull request to help if I'm stack to do it.

**Comment by pokutuna** [comment]
I'm working this on #3.
Please give me advice if you like. I'm a noob of `Type::Tiny`.

I would like to implement behavior similar to [`Mouse::U::TC#find_or_create_isa_type_constraint`](https://metacpan.org/source/SYOHEX/Mouse-v2.4.9/lib/Mouse/Util/TypeConstraints.pm#L425) for applications not using type library based object.
I wrapped `Type::Registry` to do that. But it seems to known too much about internal impl ddd03ddcd37ee5a5a6cdc73dabe74e000e5c04c5.
Is there no other good way?

<del>And I want to know a good way to translate `{ a => 'Str', b => 'ArrayRef[Int]' }` to `Dict[a => Str, b => ArrayRef[Int], slurpy Any]`. I'm checking each key and value now.</del>

`Dict[ (map { $_ => _type($hash->{$_}, $registry) } keys %$hash), slurpy Any ];` is works fine!

**Comment by pokutuna** [comment]
#3 merged.
